services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: car-price-prediction:latest
    ports:
      - "8000:8000"
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      APP_RELOAD: "false"
